# Generated by Django 4.1.1 on 2022-09-09 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="possessedingredient",
            name="expire_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="possessedingredient",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
