# Generated by Django 4.1.1 on 2022-09-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("gluten_free", models.BooleanField()),
                ("lactose_free", models.BooleanField()),
                ("vegetarian", models.BooleanField()),
                ("vegan", models.BooleanField()),
                ("pork_free", models.BooleanField()),
                ("sweet", models.BooleanField()),
                ("salty", models.BooleanField()),
                ("ingredients", models.ManyToManyField(to="ingredients.ingredient")),
            ],
        ),
    ]
